[tool.black]
line-length = 150
target-version = ["py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 150
combine_as_imports = true
combine_star = true

[tool.pyright]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = "warning"