vocabulary = {
    "Wie heißt du?": "Tu t'appelles comment?",
    "Ich heiße Leo. Und du?": "Je m'appelle Leo. Et toi?",
    "Wie alt bist du?": "Tu as quel âge?",
    "Ich bin 14 Jahre Alt. Und du?": "J'ai 14 ans. Et toi?",
    "Ich bin in der achten Klasse.": "Je suis en quatrième.",
    "Hast du Geschwister?": "Tu as des frères et soeurs?",
    "Ich habe einen Bruder. / Ich habe keine Geschwister": "J'ai un frère. / Je n'ai pas de frères et soeurs.",
    "Hast du ein Haustier?": "Tu as un animal?",
    "Ich habe einen Hund. / Ich habe kein Haustier.": "J'ai un chien. / Je n'ai pas d'animal.",
    "Meine Eltern sind zusammen/getrennt.": "Mon parents sont ensembles/séparés.",
    "Ich habe eine Allergie.": "J'ai un allergie.",
    "Ich esse kein Fleisch, weil ich Vegetarier/in bin": "Je ne mange pas de viande, parce que je suis végétarien/ne.",
    "Fußball ist nicht mein Ding.": "Le foot ce n'est pas mon truc",
    "Ich mag / liebe Videospiele.": "J'aime / J'adore les jeux vidéo",
    "Ich mag / liebe es, Minecraft zu spielen": "J'aime / J'adore joéur á Minecraft",
    "Ich hasse / mag Shoppen nicht (so sehr)": "Je n'aime pas / Je deteste la shopping",
    "Ich hasse es / mag es nicht (so sehr) zu arbeiten.": "Je n'aime pas / Je deteste travailler.",
    "Ich bin ein Fan von Kylian Mbappé.": "Je suis fan de Kylian Mbappé",
    "Pomme ist mein Lieblingssängerin.": "Pomme est ma chanteuse préferée.",
    "Ich bevorzuge es, (Museen zu besichtigen).": "Moi, je préfère (visiter des musées)",
    "Für mich, ist Sport der Horror!": "Pour moi, le sport c'est l'horreur",
    "Ich treibe Sport/ klettere / spiele Gitarre.": "Je fais du sport / de l'escalade / de la guitare."
}