name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  DIR: Korii-Bot
  NAME: korii-bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd $DIR
            git pull
            docker build -t $NAME .
            docker stop $NAME
            docker rm $NAME
            docker run --name $NAME -d $NAME