name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update the bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd personal/Korii-Bot
            git pull
            sudo docker build -t korii-bot .
            sudo docker stop korii-bot
            sudo docker rm korii-bot
            sudo docker run --name korii-bot -d korii-bot